name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Test
        run: mvn -B verify
      - name: Build with Maven
        run: mvn install
      - name: Generate sample project
        run: mvn -B archetype:generate -DarchetypeGroupId=com.lightbend -DarchetypeArtifactId=maven-archetype-akkasls -DarchetypeVersion=1.0-SNAPSHOT -DgroupId=com.example -DartifactId=generated-project
        working-directory: ${{ runner.temp }}
      - name: Compile sample project
        run: mvn -B compile
        working-directory: ${{ runner.temp }}/generated-project
      - name: Spin up proxy in background
        run: docker-compose -f docker-compose.yml -f docker-compose.linux.yml up -d
        working-directory: ${{ runner.temp }}/generated-project
      - name: Run service in background
        run: mvn exec:java&
        working-directory: ${{ runner.temp }}/generated-project
      - name: Verify expected error is returned from request once services are running
        timeout-minutes: 2
        run: |
          echo "Waiting for service to be running"
          until curl localhost:8080; do sleep 5; done
          echo "Waiting for proxy to respond"
          until curl -XPOST localhost:9000/com.example.MyServiceEntity/GetValue -H "Content-Type:application/json" -d '{"entityId":"test"}' -o response.txt; do sleep 5; done
          echo "Validating expected error message"
          test "$(cat response.txt)" = 'The command handler for `GetValue` is not implemented, yet'
        working-directory: ${{ runner.temp }}

  deploy:
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: bintray-lightbend-akkaserverless
          server-username: BINTRAY_USER
          server-password: BINTRAY_PASS
      - name: Set version
        run: mvn -B versions:set -DnewVersion="$(git tag|cut -c2-)"
      - name: Publish
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
        run: mvn -B -DskipTests=true deploy
