name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  verify-event-sourced-entity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Test
        run: mvn -B verify
      - name: Build with Maven
        run: mvn install
      - name: Generate Event Sourced entity project
        run: mvn -B archetype:generate -DarchetypeGroupId=com.lightbend -DarchetypeArtifactId=maven-archetype-akkasls-event-sourced-entity -DarchetypeVersion=1.0-SNAPSHOT -DgroupId=com.example -DartifactId=generated-project
        working-directory: ${{ runner.temp }}
      - name: Compile sample project
        run: mvn -B compile
        working-directory: ${{ runner.temp }}/generated-project
      - name: Spin up proxy in background
        run: docker-compose -f docker-compose.yml -f docker-compose.linux.yml up -d
        working-directory: ${{ runner.temp }}/generated-project
      - name: Run service in background
        run: mvn exec:java&
        env:
          HOST: "0.0.0.0"
        working-directory: ${{ runner.temp }}/generated-project
      - name: Verify expected error is returned from request once services are running
        timeout-minutes: 2
        run: |
          echo "Waiting for service to be running"
          until curl localhost:8080; do sleep 5; done
          echo "Waiting for proxy to respond"
          until curl -XPOST localhost:9000/com.example.MyServiceEntity/GetValue -H "Content-Type:application/json" -d '{"entityId":"test"}' -o response.txt; do sleep 5; done
          echo "Validating expected error message"
          test "$(cat response.txt)" = 'The command handler for `GetValue` is not implemented, yet'
        working-directory: ${{ runner.temp }}

  verify-value-entity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Test
        run: mvn -B verify
      - name: Build with Maven
        run: mvn install
      - name: Generate Value entity project
        run: mvn -B archetype:generate -DarchetypeGroupId=com.lightbend -DarchetypeArtifactId=maven-archetype-akkasls-value-entity -DarchetypeVersion=1.0-SNAPSHOT -DgroupId=com.example -DartifactId=generated-project
        working-directory: ${{ runner.temp }}
      - name: Compile sample project
        run: mvn -B compile
        working-directory: ${{ runner.temp }}/generated-project
      - name: Spin up proxy in background
        run: docker-compose -f docker-compose.yml -f docker-compose.linux.yml up -d
        working-directory: ${{ runner.temp }}/generated-project
      - name: Run service in background
        run: mvn exec:java&
        env:
          HOST: "0.0.0.0"
        working-directory: ${{ runner.temp }}/generated-project
      - name: Verify expected error is returned from request once services are running
        timeout-minutes: 2
        run: |
          echo "Waiting for service to be running"
          until curl localhost:8080; do sleep 5; done
          echo "Waiting for proxy to respond"
          until curl -XPOST localhost:9000/com.example.CounterService/GetCurrentCounter -H "Content-Type:application/json" -d '{"counterId": "foo"}' -o response.txt; do sleep 5; done
          echo "Validating expected error message"
          test "$(cat response.txt)" = 'The command handler for `GetCurrentCounter` is not implemented, yet'
        working-directory: ${{ runner.temp }}

  deploy:
    runs-on: ubuntu-latest
    needs: [verify-event-sourced-entity, verify-value-entity]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: lightbend-akkaserverless-cloudsmith
          server-username: CLOUDSMITH_USER
          server-password: CLOUDSMITH_PASS
      - name: Get version from git tag
        run: echo "::set-output name=PUBLISH_VERSION::$(git describe --abbrev=0 --tags|cut -c2-)"
        id: version-tag
      - name: Set version
        run: mvn -B versions:set -DnewVersion="${{ steps.version-tag.outputs.PUBLISH_VERSION }}"
      - name: Publish
        env:
          CLOUDSMITH_USER: ${{ secrets.CLOUDSMITH_USER }}
          CLOUDSMITH_PASS: ${{ secrets.CLOUDSMITH_PASS }}
        run: mvn -B -DskipTests=true deploy
