name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: bintray-lightbend-akkaserverless
          server-username: BINTRAY_USER
          server-password: BINTRAY_PASS
      - name: Set version
        run: mvn -B versions:set -DnewVersion="$(git tag|cut -c2-)"
      - name: Test and publish
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
        run: mvn -B deploy
